### ISSUE TITLE
Upgrade to Laravel 7

### ISSUE THREAD

**Issue by yukidaruma** [salmon-stats/api#11]
**Resources**
* https://readouble.com/laravel/7.x/ja/upgrade.html
* https://github.com/laravel/laravel/compare/6.x...master

**TODOs**
* [ ] CORS
  * [x] Upgrade
  * Test if
     * [x] GET request works
     * [x] POST request works
     * [x] Upload test works
     * [x] Stateful requests works
     * [ ] ~`tkgstrator/Salmonia` works~ (unable to run python 2.7 on my environment)
* [x] Check diff
* [x] `composer update`
* ~~Update outdated dependencies (`composer outdated`)~~ (should be tracked in other issues)
